Personal access token

diff --git a/.github/workflows/compile-docs.yml b/.github/workflows/compile-docs.yml
--- a/.github/workflows/compile-docs.yml
+++ b/.github/workflows/compile-docs.yml
@@ -45,17 +45,17 @@ jobs:
       - name: Copy github action over so that workflow_dispatch works on GitHub web UI
         run: cp -r ./.github ./docs/.github
 
-      - name: Verify then add GitHub SSH key
-        run: |
-          [ "$( ssh-keyscan -t rsa github.com | tee github-key-temp | ssh-keygen -lf - 2>/dev/null )" \
-          = "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)" ] \
-          || { printf "Invalid GitHub SSH key" >&2; exit 1; }
-          mkdir ~/.ssh
-          cat github-key-temp >>~/.ssh/known_hosts
-          eval "$( ssh-agent -s )"
-          <<EOF ssh-add -
-          ${{ secrets.PUSH_TO_DOCS_SECRET }}
-          EOF
+      #- name: Verify then add GitHub SSH key
+      #  run: |
+      #    [ "$( ssh-keyscan -t rsa github.com | tee github-key-temp | ssh-keygen -lf - 2>/dev/null )" \
+      #    = "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)" ] \
+      #    || { printf "Invalid GitHub SSH key" >&2; exit 1; }
+      #    mkdir ~/.ssh
+      #    cat github-key-temp >>~/.ssh/known_hosts
+      #    eval "$( ssh-agent -s )"
+      #    <<EOF ssh-add -
+      #    ${{ secrets.PUSH_TO_DOCS_SECRET }}
+      #    EOF
 
       - name: Remove ./.gitignore that ignores ./docs
         run: rm ./.gitignore
@@ -69,7 +69,8 @@ jobs:
         run: |
           git add docs
           git config user.email "bot@users.noreply.github.com"
-          git config user.name "GitHub Actions: ${{ env.GITHUB_ACTION }}"
+          git config user.name "senlin-stars"
+          git config user.name "${{ secrets.WRITER_PAT }}"
           git commit -m "publishing docs $( date +'%Y-%m-%d %H-%M-%S' )"
           git subtree split --prefix docs --branch docs
           git checkout docs
