Add parse step

diff --git a/.github/workflows/compile-docs.yml b/.github/workflows/compile-docs.yml
--- a/.github/workflows/compile-docs.yml
+++ b/.github/workflows/compile-docs.yml
@@ -28,3 +28,29 @@ jobs:
 
       - name: Parse
         run:  parse.sh "./tetra/target/debug/tetra-cli"
+
+      - name: Verify then add GitHub SSH key
+        run: |
+          [ "$( ssh-keyscan -t rsa github.com | tee github-key-temp | ssh-keygen -lf - 2>/dev/null )" \
+          = "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)" ] \
+          || { printf "Invalid GitHub SSH key" >&2; exit 1; }
+          mkdir ~/.ssh
+          cat github-key-temp >>~/.ssh/known_hosts
+          eval "$( ssh-agent -s )"
+          <<EOF ssh-add -
+          ${{ secrets.PUSH_TO_DOCS_SECRET }}
+          EOF
+
+      - name: Push to gh_pages branch
+        env:
+          SSH_AUTH_SOCKET: /tmp/ssh_agent.sock
+        run: |
+          git add public
+          git config user.email "bot@users.noreply.github.com"
+          git config user.name "GitHub Actions: ${{ env.GITHUB_ACTION }}"
+          git commit -m 'publishing public'
+          git subtree split --prefix public --branch docs
+          git checkout docs
+          git status
+          git remote -v
+          git push --force origin docs
